global using Xunit;
global using Bogus;
global using FC.Codeflix.Catalog.IntegrationTests.Common;
global using FC.Codeflix.Catalog.Domain.Entity;
global using FC.Codeflix.Catalog.Infra.Data.EF;
global using Microsoft.EntityFrameworkCore;
global using FluentAssertions;
global using FC.Codeflix.Catalog.Application.Exception;
global using FC.Codeflix.Catalog.Domain.SeedWork.SearchableRepository;